describe: danet
model_name: danet_alpha0.8
path:
  model_dir: ../../user_data/model_data
  resume_path: ../../user_data/model_data/05212306danet_alpha0.8/model_8.pt #checkpoint .pt file for test model
  save_dir: ../../yang_data/05241035mobilenetnet/ #checkpoint save path
  test_dir: data/yangtianyun/dataset/MM_class/ps_detection_divide #train/test split path
test:
  batchSize: 256
  fp16: 1
  imageSize: 320
  resize: 512
  stride: 4
  zp: 0
train:
  aug: 0
  balance: 1
  batchSize: 8
  fake_weight: 0.8
  fp16: 1
  hard_aug: 0
  imageSize: 320
  lr: 0.0001
  n_input: 3
  nclass: 2
  niter: 100
  # some unimportant output
  outf: ../../user_data/model_data
  real_cls: 1
  remove: 1
  resize: 512
  resume: 0
  save_step: 1
  step_save: 1
  stride: 4
  th: 0.5
  # train/test split path
  train_path: C:\Users\Think\Desktop\media\DANet_baseline\train\data\yangtianyun\dataset\MM_class\ps_detection_divide\psbattle_orisize_yty_train\annotations\psbattle_orisize_yty_train.txt
  val_path: C:\Users\Think\Desktop\media\DANet_baseline\train\data\yangtianyun\dataset\MM_class\ps_detection_divide\psbattle_orisize_yty_val\annotations\psbattle_orisize_yty_val.txt
  writer_root: ../../user_data/tensorlog
  zp: 0
